export type {
  Builtin,
  KeyofBase,
  Prettify,
  Primitive,
  StrictExclude,
  StrictExtract,
  StrictOmit,
  Writable,
  AsyncOrSync,
  AsyncOrSyncType,
  Dictionary,
  Merge,
  MergeN,
  Newable,
  NonNever,
  OmitProperties,
  Opaque,
  PathValue,
  Paths,
  PickProperties,
  SafeDictionary,
  UnionToIntersection,
  ValueOf,
  XOR,
  MarkOptional,
  MarkReadonly,
  MarkRequired,
  MarkWritable,
  Buildable,
  DeepNonNullable,
  DeepNullable,
  DeepOmit,
  DeepPartial,
  DeepPick,
  DeepReadonly,
  DeepRequired,
  DeepUndefinable,
  DeepWritable,
  StrictDeepOmit,
  StrictDeepPick,
  OptionalKeys,
  PickKeys,
  ReadonlyKeys,
  WritableKeys,
  Exact,
  IsAny,
  IsNever,
  IsUnknown,
  IsTuple,
  NonEmptyObject,
  AnyArray,
  ArrayOrSingle,
  ElementOf,
  Head,
  NonEmptyArray,
  ReadonlyArrayOrSingle,
  Tail,
  Tuple,
  CamelCase,
  DeepCamelCaseProperties,
  AnyFunction,
  PredicateFunction,
  PredicateType
} from 'ts-essentials'
export type ObjectKey = string | number | symbol
export type Fn<Args extends any[] = any[], Return = any> = (...args: Args) => Return
export type AsyncFn<Args extends any[] = any[], Return = any> = (...args: Args) => Promise<Return>
export type PickPromise<T> = T extends Promise<infer U> ? U : T
export type PickIterable<T> = T extends Iterable<infer U> ? U : T
export type Includes<T extends any[], Check> = Check extends T[number] ? true : false
export type ArrayLast<T extends any[]> = T extends [...any[], infer U] ? U : never
