import { expect, test, describe } from 'bun:test'
import {
  isArray,
  isAsyncFunction,
  isBoolean,
  isDate,
  isEmpty,
  isFunction,
  isMap,
  isNull,
  isNumber,
  isObject,
  isPromise,
  isRegExp,
  isSet,
  isString,
  isSymbol,
  isUndefined,
  isWeakMap,
  isWeakSet
} from '../src'

describe('validator.util', () => {
  class A {
    constructor() {}
  }

  test('isObject', () => {
    expect(isObject('a')).toBe(false)
    expect(isObject(true)).toBe(false)
    expect(isObject(false)).toBe(false)
    expect(isObject(1)).toBe(false)
    expect(isObject(1.2)).toBe(false)
    expect(isObject(null)).toBe(false)
    expect(isObject(undefined)).toBe(false)
    expect(isObject(new A())).toBe(true)
    expect(isObject({})).toBe(true)
    expect(isObject([])).toBe(false)
    expect(isObject(new RegExp('a'))).toBe(false)
    expect(isObject(Symbol())).toBe(false)
    expect(isObject(1n)).toBe(false)
    expect(isObject(new Date())).toBe(false)
    expect(isObject(new Error())).toBe(false)
    expect(isObject(new Map())).toBe(false)
    expect(isObject(new Set())).toBe(false)
    expect(isObject(new WeakMap())).toBe(false)
    expect(isObject(new WeakSet())).toBe(false)
    expect(isObject(function () {})).toBe(false)
    expect(isObject(async function () {})).toBe(false)
    expect(isObject(new Promise(() => {}))).toBe(false)
    expect(isObject(new Promise((resolve) => resolve(1)))).toBe(false)
  })

  test('isArray', () => {
    expect(isArray('a')).toBe(false)
    expect(isArray(true)).toBe(false)
    expect(isArray(false)).toBe(false)
    expect(isArray(1)).toBe(false)
    expect(isArray(1.2)).toBe(false)
    expect(isArray(null)).toBe(false)
    expect(isArray(undefined)).toBe(false)
    expect(isArray(new A())).toBe(false)
    expect(isArray({})).toBe(false)
    expect(isArray([])).toBe(true)
    expect(isArray(new RegExp('a'))).toBe(false)
    expect(isArray(Symbol())).toBe(false)
    expect(isArray(1n)).toBe(false)
    expect(isArray(new Date())).toBe(false)
    expect(isArray(new Error())).toBe(false)
    expect(isArray(new Map())).toBe(false)
    expect(isArray(new Set())).toBe(false)
    expect(isArray(new WeakMap())).toBe(false)
    expect(isArray(new WeakSet())).toBe(false)
    expect(isArray(function () {})).toBe(false)
    expect(isArray(async function () {})).toBe(false)
    expect(isArray(new Promise(() => {}))).toBe(false)
    expect(isArray(new Promise((resolve) => resolve(1)))).toBe(false)
  })

  test('isString', () => {
    expect(isString('a')).toBe(true)
    expect(isString(true)).toBe(false)
    expect(isString(false)).toBe(false)
    expect(isString(1)).toBe(false)
    expect(isString(1.2)).toBe(false)
    expect(isString(null)).toBe(false)
    expect(isString(undefined)).toBe(false)
    expect(isString(new A())).toBe(false)
    expect(isString({})).toBe(false)
    expect(isString([])).toBe(false)
    expect(isString(new RegExp('a'))).toBe(false)
    expect(isString(Symbol())).toBe(false)
    expect(isString(1n)).toBe(false)
    expect(isString(new Date())).toBe(false)
    expect(isString(new Error())).toBe(false)
    expect(isString(new Map())).toBe(false)
    expect(isString(new Set())).toBe(false)
    expect(isString(new WeakMap())).toBe(false)
    expect(isString(new WeakSet())).toBe(false)
    expect(isString(function () {})).toBe(false)
    expect(isString(async function () {})).toBe(false)
    expect(isString(new Promise(() => {}))).toBe(false)
    expect(isString(new Promise((resolve) => resolve(1)))).toBe(false)
  })

  test('isNumber', () => {
    expect(isNumber('a')).toBe(false)
    expect(isNumber(true)).toBe(false)
    expect(isNumber(false)).toBe(false)
    expect(isNumber(1)).toBe(true)
    expect(isNumber(1.2)).toBe(true)
    expect(isNumber(NaN)).toBe(false)
    expect(isNumber(NaN, { NaN: true })).toBe(true)
    expect(isNumber(Infinity)).toBe(false)
    expect(isNumber(Infinity, { Infinitys: true })).toBe(true)
    expect(isNumber(-Infinity)).toBe(false)
    expect(isNumber(-Infinity, { Infinitys: true })).toBe(true)
    expect(isNumber(Number.POSITIVE_INFINITY)).toBe(false)
    expect(isNumber(Number.POSITIVE_INFINITY, { Infinitys: true })).toBe(true)
    expect(isNumber(Number.NEGATIVE_INFINITY)).toBe(false)
    expect(isNumber(Number.NEGATIVE_INFINITY, { Infinitys: true })).toBe(true)
    expect(isNumber(null)).toBe(false)
    expect(isNumber(undefined)).toBe(false)
    expect(isNumber(new A())).toBe(false)
    expect(isNumber({})).toBe(false)
    expect(isNumber([])).toBe(false)
    expect(isNumber(new RegExp('a'))).toBe(false)
    expect(isNumber(Symbol())).toBe(false)
    expect(isNumber(1n)).toBe(false)
    expect(isNumber(new Date())).toBe(false)
    expect(isNumber(new Error())).toBe(false)
    expect(isNumber(new Map())).toBe(false)
    expect(isNumber(new Set())).toBe(false)
    expect(isNumber(new WeakMap())).toBe(false)
    expect(isNumber(new WeakSet())).toBe(false)
    expect(isNumber(function () {})).toBe(false)
    expect(isNumber(async function () {})).toBe(false)
    expect(isNumber(new Promise(() => {}))).toBe(false)
    expect(isNumber(new Promise((resolve) => resolve(1)))).toBe(false)
  })

  test('isBoolean', () => {
    expect(isBoolean('a')).toBe(false)
    expect(isBoolean(true)).toBe(true)
    expect(isBoolean(false)).toBe(true)
    expect(isBoolean(1)).toBe(false)
    expect(isBoolean(1.2)).toBe(false)
    expect(isBoolean(null)).toBe(false)
    expect(isBoolean(undefined)).toBe(false)
    expect(isBoolean(new A())).toBe(false)
    expect(isBoolean({})).toBe(false)
    expect(isBoolean([])).toBe(false)
    expect(isBoolean(new RegExp('a'))).toBe(false)
    expect(isBoolean(Symbol())).toBe(false)
    expect(isBoolean(1n)).toBe(false)
    expect(isBoolean(new Date())).toBe(false)
    expect(isBoolean(new Error())).toBe(false)
    expect(isBoolean(new Map())).toBe(false)
    expect(isBoolean(new Set())).toBe(false)
    expect(isBoolean(new WeakMap())).toBe(false)
    expect(isBoolean(new WeakSet())).toBe(false)
    expect(isBoolean(function () {})).toBe(false)
    expect(isBoolean(async function () {})).toBe(false)
    expect(isBoolean(new Promise(() => {}))).toBe(false)
    expect(isBoolean(new Promise((resolve) => resolve(1)))).toBe(false)
  })

  test('isFunction', () => {
    expect(isFunction('a')).toBe(false)
    expect(isFunction(true)).toBe(false)
    expect(isFunction(false)).toBe(false)
    expect(isFunction(1)).toBe(false)
    expect(isFunction(1.2)).toBe(false)
    expect(isFunction(null)).toBe(false)
    expect(isFunction(undefined)).toBe(false)
    expect(isFunction(new A())).toBe(false)
    expect(isFunction({})).toBe(false)
    expect(isFunction([])).toBe(false)
    expect(isFunction(new RegExp('a'))).toBe(false)
    expect(isFunction(Symbol())).toBe(false)
    expect(isFunction(1n)).toBe(false)
    expect(isFunction(new Date())).toBe(false)
    expect(isFunction(new Error())).toBe(false)
    expect(isFunction(new Map())).toBe(false)
    expect(isFunction(new Set())).toBe(false)
    expect(isFunction(new WeakMap())).toBe(false)
    expect(isFunction(new WeakSet())).toBe(false)
    expect(isFunction(function () {})).toBe(true)
    expect(isFunction(async function () {})).toBe(true)
    expect(isFunction(new Promise(() => {}))).toBe(false)
    expect(isFunction(new Promise((resolve) => resolve(1)))).toBe(false)
  })

  test('isAsyncFunction', () => {
    expect(isAsyncFunction(function () {})).toBe(false)
    expect(isAsyncFunction(async function () {})).toBe(true)
    expect(isAsyncFunction(new Promise(() => {}))).toBe(false)
    expect(isAsyncFunction(new Promise((resolve) => resolve(1)))).toBe(false)
  })

  test('isUndefined', () => {
    expect(isUndefined('a')).toBe(false)
    expect(isUndefined(true)).toBe(false)
    expect(isUndefined(false)).toBe(false)
    expect(isUndefined(1)).toBe(false)
    expect(isUndefined(1.2)).toBe(false)
    expect(isUndefined(null)).toBe(false)
    expect(isUndefined(undefined)).toBe(true)
    expect(isUndefined(new A())).toBe(false)
    expect(isUndefined({})).toBe(false)
    expect(isUndefined([])).toBe(false)
    expect(isUndefined(new RegExp('a'))).toBe(false)
    expect(isUndefined(Symbol())).toBe(false)
    expect(isUndefined(1n)).toBe(false)
    expect(isUndefined(new Date())).toBe(false)
    expect(isUndefined(new Error())).toBe(false)
    expect(isUndefined(new Map())).toBe(false)
    expect(isUndefined(new Set())).toBe(false)
    expect(isUndefined(new WeakMap())).toBe(false)
    expect(isUndefined(new WeakSet())).toBe(false)
    expect(isUndefined(function () {})).toBe(false)
    expect(isUndefined(async function () {})).toBe(false)
    expect(isUndefined(new Promise(() => {}))).toBe(false)
    expect(isUndefined(new Promise((resolve) => resolve(1)))).toBe(false)
  })

  test('isNull', () => {
    expect(isNull('a')).toBe(false)
    expect(isNull(true)).toBe(false)
    expect(isNull(false)).toBe(false)
    expect(isNull(1)).toBe(false)
    expect(isNull(1.2)).toBe(false)
    expect(isNull(null)).toBe(true)
    expect(isNull(undefined)).toBe(false)
    expect(isNull(new A())).toBe(false)
    expect(isNull({})).toBe(false)
    expect(isNull([])).toBe(false)
    expect(isNull(new RegExp('a'))).toBe(false)
    expect(isNull(Symbol())).toBe(false)
    expect(isNull(1n)).toBe(false)
    expect(isNull(new Date())).toBe(false)
    expect(isNull(new Error())).toBe(false)
    expect(isNull(new Map())).toBe(false)
    expect(isNull(new Set())).toBe(false)
    expect(isNull(new WeakMap())).toBe(false)
    expect(isNull(new WeakSet())).toBe(false)
    expect(isNull(function () {})).toBe(false)
    expect(isNull(async function () {})).toBe(false)
    expect(isNull(new Promise(() => {}))).toBe(false)
    expect(isNull(new Promise((resolve) => resolve(1)))).toBe(false)
  })

  test('isRegExp', () => {
    expect(isRegExp('a')).toBe(false)
    expect(isRegExp(true)).toBe(false)
    expect(isRegExp(false)).toBe(false)
    expect(isRegExp(1)).toBe(false)
    expect(isRegExp(1.2)).toBe(false)
    expect(isRegExp(null)).toBe(false)
    expect(isRegExp(undefined)).toBe(false)
    expect(isRegExp(new A())).toBe(false)
    expect(isRegExp({})).toBe(false)
    expect(isRegExp([])).toBe(false)
    expect(isRegExp(new RegExp('a'))).toBe(true)
    expect(isRegExp(Symbol())).toBe(false)
    expect(isRegExp(1n)).toBe(false)
    expect(isRegExp(new Date())).toBe(false)
    expect(isRegExp(new Error())).toBe(false)
    expect(isRegExp(new Map())).toBe(false)
    expect(isRegExp(new Set())).toBe(false)
    expect(isRegExp(new WeakMap())).toBe(false)
    expect(isRegExp(new WeakSet())).toBe(false)
    expect(isRegExp(function () {})).toBe(false)
    expect(isRegExp(async function () {})).toBe(false)
    expect(isRegExp(new Promise(() => {}))).toBe(false)
    expect(isRegExp(new Promise((resolve) => resolve(1)))).toBe(false)
  })

  test('isDate', () => {
    expect(isDate('a')).toBe(false)
    expect(isDate(true)).toBe(false)
    expect(isDate(false)).toBe(false)
    expect(isDate(1)).toBe(false)
    expect(isDate(1.2)).toBe(false)
    expect(isDate(null)).toBe(false)
    expect(isDate(undefined)).toBe(false)
    expect(isDate(new A())).toBe(false)
    expect(isDate({})).toBe(false)
    expect(isDate([])).toBe(false)
    expect(isDate(new RegExp('a'))).toBe(false)
    expect(isDate(Symbol())).toBe(false)
    expect(isDate(1n)).toBe(false)
    expect(isDate(new Date())).toBe(true)
    expect(isDate(new Error())).toBe(false)
    expect(isDate(new Map())).toBe(false)
    expect(isDate(new Set())).toBe(false)
    expect(isDate(new WeakMap())).toBe(false)
    expect(isDate(new WeakSet())).toBe(false)
    expect(isDate(function () {})).toBe(false)
    expect(isDate(async function () {})).toBe(false)
    expect(isDate(new Promise(() => {}))).toBe(false)
    expect(isDate(new Promise((resolve) => resolve(1)))).toBe(false)
  })

  test('isSymbol', () => {
    expect(isSymbol('a')).toBe(false)
    expect(isSymbol(true)).toBe(false)
    expect(isSymbol(false)).toBe(false)
    expect(isSymbol(1)).toBe(false)
    expect(isSymbol(1.2)).toBe(false)
    expect(isSymbol(null)).toBe(false)
    expect(isSymbol(undefined)).toBe(false)
    expect(isSymbol(new A())).toBe(false)
    expect(isSymbol({})).toBe(false)
    expect(isSymbol([])).toBe(false)
    expect(isSymbol(new RegExp('a'))).toBe(false)
    expect(isSymbol(Symbol())).toBe(true)
    expect(isSymbol(1n)).toBe(false)
    expect(isSymbol(new Date())).toBe(false)
    expect(isSymbol(new Error())).toBe(false)
    expect(isSymbol(new Map())).toBe(false)
    expect(isSymbol(new Set())).toBe(false)
    expect(isSymbol(new WeakMap())).toBe(false)
    expect(isSymbol(new WeakSet())).toBe(false)
    expect(isSymbol(function () {})).toBe(false)
    expect(isSymbol(async function () {})).toBe(false)
    expect(isSymbol(new Promise(() => {}))).toBe(false)
    expect(isSymbol(new Promise((resolve) => resolve(1)))).toBe(false)
  })

  test('isPromise', () => {
    expect(isPromise('a')).toBe(false)
    expect(isPromise(true)).toBe(false)
    expect(isPromise(false)).toBe(false)
    expect(isPromise(1)).toBe(false)
    expect(isPromise(1.2)).toBe(false)
    expect(isPromise(null)).toBe(false)
    expect(isPromise(undefined)).toBe(false)
    expect(isPromise(new A())).toBe(false)
    expect(isPromise({})).toBe(false)
    expect(isPromise([])).toBe(false)
    expect(isPromise(new RegExp('a'))).toBe(false)
    expect(isPromise(Symbol())).toBe(false)
    expect(isPromise(1n)).toBe(false)
    expect(isPromise(new Date())).toBe(false)
    expect(isPromise(new Error())).toBe(false)
    expect(isPromise(new Map())).toBe(false)
    expect(isPromise(new Set())).toBe(false)
    expect(isPromise(new WeakMap())).toBe(false)
    expect(isPromise(new WeakSet())).toBe(false)
    expect(isPromise(function () {})).toBe(false)
    expect(isPromise(async function () {})).toBe(false)
    expect(isPromise(new Promise(() => {}))).toBe(true)
    expect(isPromise(new Promise((resolve) => resolve(1)))).toBe(true)
  })

  test('isMap', () => {
    expect(isMap('a')).toBe(false)
    expect(isMap(true)).toBe(false)
    expect(isMap(false)).toBe(false)
    expect(isMap(1)).toBe(false)
    expect(isMap(1.2)).toBe(false)
    expect(isMap(null)).toBe(false)
    expect(isMap(undefined)).toBe(false)
    expect(isMap(new A())).toBe(false)
    expect(isMap({})).toBe(false)
    expect(isMap([])).toBe(false)
    expect(isMap(new RegExp('a'))).toBe(false)
    expect(isMap(Symbol())).toBe(false)
    expect(isMap(1n)).toBe(false)
    expect(isMap(new Date())).toBe(false)
    expect(isMap(new Error())).toBe(false)
    expect(isMap(new Map())).toBe(true)
    expect(isMap(new Set())).toBe(false)
    expect(isMap(new WeakMap())).toBe(false)
    expect(isMap(new WeakSet())).toBe(false)
    expect(isMap(function () {})).toBe(false)
    expect(isMap(async function () {})).toBe(false)
    expect(isMap(new Promise(() => {}))).toBe(false)
    expect(isMap(new Promise((resolve) => resolve(1)))).toBe(false)
  })

  test('isSet', () => {
    expect(isSet('a')).toBe(false)
    expect(isSet(true)).toBe(false)
    expect(isSet(false)).toBe(false)
    expect(isSet(1)).toBe(false)
    expect(isSet(1.2)).toBe(false)
    expect(isSet(null)).toBe(false)
    expect(isSet(undefined)).toBe(false)
    expect(isSet(new A())).toBe(false)
    expect(isSet({})).toBe(false)
    expect(isSet([])).toBe(false)
    expect(isSet(new RegExp('a'))).toBe(false)
    expect(isSet(Symbol())).toBe(false)
    expect(isSet(1n)).toBe(false)
    expect(isSet(new Date())).toBe(false)
    expect(isSet(new Error())).toBe(false)
    expect(isSet(new Map())).toBe(false)
    expect(isSet(new Set())).toBe(true)
    expect(isSet(new WeakMap())).toBe(false)
    expect(isSet(new WeakSet())).toBe(false)
    expect(isSet(function () {})).toBe(false)
    expect(isSet(async function () {})).toBe(false)
    expect(isSet(new Promise(() => {}))).toBe(false)
    expect(isSet(new Promise((resolve) => resolve(1)))).toBe(false)
  })

  test('isWeakMap', () => {
    expect(isWeakMap('a')).toBe(false)
    expect(isWeakMap(true)).toBe(false)
    expect(isWeakMap(false)).toBe(false)
    expect(isWeakMap(1)).toBe(false)
    expect(isWeakMap(1.2)).toBe(false)
    expect(isWeakMap(null)).toBe(false)
    expect(isWeakMap(undefined)).toBe(false)
    expect(isWeakMap(new A())).toBe(false)
    expect(isWeakMap({})).toBe(false)
    expect(isWeakMap([])).toBe(false)
    expect(isWeakMap(new RegExp('a'))).toBe(false)
    expect(isWeakMap(Symbol())).toBe(false)
    expect(isWeakMap(1n)).toBe(false)
    expect(isWeakMap(new Date())).toBe(false)
    expect(isWeakMap(new Error())).toBe(false)
    expect(isWeakMap(new Map())).toBe(false)
    expect(isWeakMap(new Set())).toBe(false)
    expect(isWeakMap(new WeakMap())).toBe(true)
    expect(isWeakMap(new WeakSet())).toBe(false)
    expect(isWeakMap(function () {})).toBe(false)
    expect(isWeakMap(async function () {})).toBe(false)
    expect(isWeakMap(new Promise(() => {}))).toBe(false)
    expect(isWeakMap(new Promise((resolve) => resolve(1)))).toBe(false)
  })

  test('isWeakSet', () => {
    expect(isWeakSet('a')).toBe(false)
    expect(isWeakSet(true)).toBe(false)
    expect(isWeakSet(false)).toBe(false)
    expect(isWeakSet(1)).toBe(false)
    expect(isWeakSet(1.2)).toBe(false)
    expect(isWeakSet(null)).toBe(false)
    expect(isWeakSet(undefined)).toBe(false)
    expect(isWeakSet(new A())).toBe(false)
    expect(isWeakSet({})).toBe(false)
    expect(isWeakSet([])).toBe(false)
    expect(isWeakSet(new RegExp('a'))).toBe(false)
    expect(isWeakSet(Symbol())).toBe(false)
    expect(isWeakSet(1n)).toBe(false)
    expect(isWeakSet(new Date())).toBe(false)
    expect(isWeakSet(new Error())).toBe(false)
    expect(isWeakSet(new Map())).toBe(false)
    expect(isWeakSet(new Set())).toBe(false)
    expect(isWeakSet(new WeakMap())).toBe(false)
    expect(isWeakSet(new WeakSet())).toBe(true)
    expect(isWeakSet(function () {})).toBe(false)
    expect(isWeakSet(async function () {})).toBe(false)
    expect(isWeakSet(new Promise(() => {}))).toBe(false)
    expect(isWeakSet(new Promise((resolve) => resolve(1)))).toBe(false)
  })

  test('isEmpty', () => {
    expect(isEmpty('a')).toBe(false)
    expect(isEmpty(true)).toBe(false)
    expect(isEmpty(false)).toBe(false)
    expect(isEmpty(1)).toBe(false)
    expect(isEmpty(1.2)).toBe(false)
    expect(isEmpty(null)).toBe(true)
    expect(isEmpty(undefined)).toBe(true)
    expect(isEmpty(new A())).toBe(true)
    expect(isEmpty({})).toBe(true)
    expect(isEmpty([])).toBe(true)
    expect(isEmpty(new RegExp('a'))).toBe(false)
    expect(isEmpty(Symbol())).toBe(false)
    expect(isEmpty(1n)).toBe(false)
    expect(isEmpty(new Date())).toBe(false)
    expect(isEmpty(new Error())).toBe(false)
    expect(isEmpty(new Map())).toBe(true)
    expect(isEmpty(new Set())).toBe(true)
    expect(isEmpty(new WeakMap())).toBe(false)
    expect(isEmpty(new WeakSet())).toBe(false)
    expect(isEmpty(function () {})).toBe(false)
    expect(isEmpty(async function () {})).toBe(false)
    expect(isEmpty(new Promise(() => {}))).toBe(false)
    expect(isEmpty(new Promise((resolve) => resolve(1)))).toBe(false)
  })

  // test('isRgbColor', () => {
  //   expect(isRgbColor('rgb(1, 1, 1)')).toBe(true)
  //   expect(isRgbColor('rgb(255, 255, 255)')).toBe(true)
  //   expect(isRgbColor('rgb(1, 1, 251)')).toBe(true)
  //   expect(isRgbColor('rgba(255, 255, 255, 0.5)')).toBe(true)
  //   expect(isRgbColor('rgba(1, 1, 1, 1)')).toBe(true)
  //   expect(isRgbColor('rgba(1, 1, 1, .1)')).toBe(true)
  //   expect(isRgbColor('rgba(1, 1, 1, 0.1)')).toBe(true)
  //   expect(isRgbColor('rgb(255, 255, 255, 0.5)')).toBe(true)
  //   expect(isRgbColor('rgb(1, 1, 1, 1)')).toBe(true)
  //   expect(isRgbColor('rgb(-1, 1, 1)')).toBe(false)
  //   expect(isRgbColor('rgb(256, 1, 1)')).toBe(false)
  //   expect(isRgbColor('rgb(1, -1, 1)')).toBe(false)
  //   expect(isRgbColor('rgb(1, 256, 1)')).toBe(false)
  //   expect(isRgbColor('rgb(1, 1, -1)')).toBe(false)
  //   expect(isRgbColor('rgb(1, 1, 1, 1, 1)')).toBe(false)
  //   expect(isRgbColor('rgba(1, 1, 1, xxx)')).toBe(false)
  //   expect(isRgbColor('rgba(255, 255, 255)')).toBe(false)
  // })

  // test('isHexColor', () => {
  //   expect(isHexColor('#ffff')).toBe(true)
  //   expect(isHexColor('#000')).toBe(true)
  //   expect(isHexColor('#f10')).toBe(true)
  //   expect(isHexColor('#f10f10')).toBe(true)
  //   expect(isHexColor('#f10f10')).toBe(true)
  //   expect(isHexColor('#f10f10f1')).toBe(true)

  //   expect(isHexColor('#a2')).toBe(false)
  //   expect(isHexColor('#y11')).toBe(false)
  //   expect(isHexColor('#f10f10f10')).toBe(false)
  //   expect(isHexColor('#f10f10f10f10')).toBe(false)
  //   expect(isHexColor('#f10f10f10f10')).toBe(false)
  // })
})
